//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:54:57 AM EDT 
//

package com.trp.pub.cust.model.xml1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.namespace.QName;

/**
 * <p>
 * Java class for BinaryOperation complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="BinaryOperation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://trp/inv/atlas/1.0}Expression"/>
 *         &lt;group ref="{http://trp/inv/atlas/1.0}Expression"/>
 *       &lt;/sequence>
 *       &lt;attribute name="op" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BinaryOperation", namespace = "http://trp/inv/atlas/1.0", propOrder = { "content" })
public class BinaryOperation {

    @XmlElementRefs({
            @XmlElementRef(name = "Not", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
            @XmlElementRef(name = "Group", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
            @XmlElementRef(name = "Connective", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
            @XmlElementRef(name = "ParamRef", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
            @XmlElementRef(name = "AttrRef", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
            @XmlElementRef(name = "Array", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
            @XmlElementRef(name = "Comparison", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
            @XmlElementRef(name = "Literal", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
            @XmlElementRef(name = "FunctionCall", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class) })
    protected List<JAXBElement<?>> content;
    @XmlAttribute(required = true)
    protected String op;

    /**
     * Gets the rest of the content model.
     * 
     * <p>
     * You are getting this "catch-all" property because of the following
     * reason: The field name "AttrRef" is used by two different parts of a
     * schema. See: line 186 of
     * file:/O:/workspace/IDSquerybuilderWEB/src/main/resources/atlas.xsd line
     * 186 of file:/O:/workspace/IDSquerybuilderWEB/src/main/resources/atlas.xsd
     * <p>
     * To get rid of this property, apply a property customization to one of
     * both of the following declarations to change their names: Gets the value
     * of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link UnaryOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link BinaryOperation.Group }{@code >}
     * {@link JAXBElement }{@code <}{@link BinaryOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link BinaryOperation.AttrRef }{@code >}
     * {@link JAXBElement }{@code <}{@link BinaryOperation.ParamRef }{@code >}
     * {@link JAXBElement }{@code <}{@link BinaryOperation.Array }{@code >}
     * {@link JAXBElement }{@code <}{@link BinaryOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link BinaryOperation.Literal }{@code >}
     * {@link JAXBElement }{@code <}{@link BinaryOperation.FunctionCall }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

    /**
     * Gets the value of the op property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOp() {
        return op;
    }

    /**
     * Sets the value of the op property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOp(String value) {
        this.op = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;group ref="{http://trp/inv/atlas/1.0}Expression"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "attrRefOrLiteralOrParamRef" })
    public static class Array {

        @XmlElementRefs({
                @XmlElementRef(name = "Literal", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "AttrRef", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Connective", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Array", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Group", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Comparison", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "FunctionCall", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "ParamRef", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Not", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class) })
        protected List<JAXBElement<?>> attrRefOrLiteralOrParamRef;

        /**
         * Gets the value of the attrRefOrLiteralOrParamRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the attrRefOrLiteralOrParamRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getAttrRefOrLiteralOrParamRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link BinaryOperation.Literal }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation.AttrRef }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation.Array }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation.Group }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation.FunctionCall }
         * {@code >} {@link JAXBElement }{@code <}{@link UnaryOperation }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation.ParamRef }{@code >}
         * 
         * 
         */
        public List<JAXBElement<?>> getAttrRefOrLiteralOrParamRef() {
            if (attrRefOrLiteralOrParamRef == null) {
                attrRefOrLiteralOrParamRef = new ArrayList<JAXBElement<?>>();
            }
            return this.attrRefOrLiteralOrParamRef;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class AttrRef {

        @XmlValue
        protected String value;
        @XmlAttribute(required = true)
        protected int id;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;group ref="{http://trp/inv/atlas/1.0}Expression"/>
     *         &lt;element name="Constant" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/choice>
     *       &lt;attribute name="function" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "attrRefOrLiteralOrParamRef" })
    public static class FunctionCall {

        @XmlElementRefs({
                @XmlElementRef(name = "ParamRef", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Comparison", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Connective", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Array", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Constant", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "FunctionCall", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Group", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Not", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "AttrRef", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class),
                @XmlElementRef(name = "Literal", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class) })
        protected List<JAXBElement<?>> attrRefOrLiteralOrParamRef;
        @XmlAttribute(required = true)
        protected String function;

        /**
         * Gets the value of the attrRefOrLiteralOrParamRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the attrRefOrLiteralOrParamRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getAttrRefOrLiteralOrParamRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link BinaryOperation.ParamRef }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation.Array }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation.FunctionCall }
         * {@code >} {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation.Group }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation.AttrRef }{@code >}
         * {@link JAXBElement }{@code <}{@link UnaryOperation }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryOperation.Literal }{@code >}
         * 
         * 
         */
        public List<JAXBElement<?>> getAttrRefOrLiteralOrParamRef() {
            if (attrRefOrLiteralOrParamRef == null) {
                attrRefOrLiteralOrParamRef = new ArrayList<JAXBElement<?>>();
            }
            return this.attrRefOrLiteralOrParamRef;
        }

        /**
         * Gets the value of the function property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getFunction() {
            return function;
        }

        /**
         * Sets the value of the function property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setFunction(String value) {
            this.function = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://trp/inv/atlas/1.0}Expression"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "attrRef", "literal", "paramRef",
            "array", "functionCall", "group", "comparison", "connective", "not" })
    public static class Group {

        @XmlElement(name = "AttrRef", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation.AttrRef attrRef;
        @XmlElementRef(name = "Literal", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class)
        protected JAXBElement<BinaryOperation.Literal> literal;
        @XmlElement(name = "ParamRef", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation.ParamRef paramRef;
        @XmlElement(name = "Array", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation.Array array;
        @XmlElement(name = "FunctionCall", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation.FunctionCall functionCall;
        @XmlElement(name = "Group", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation.Group group;
        @XmlElement(name = "Comparison", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation comparison;
        @XmlElement(name = "Connective", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation connective;
        @XmlElement(name = "Not", namespace = "http://trp/inv/atlas/1.0")
        protected UnaryOperation not;

        /**
         * Gets the value of the attrRef property.
         * 
         * @return possible object is {@link BinaryOperation.AttrRef }
         * 
         */
        public BinaryOperation.AttrRef getAttrRef() {
            return attrRef;
        }

        /**
         * Sets the value of the attrRef property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation.AttrRef }
         * 
         */
        public void setAttrRef(BinaryOperation.AttrRef value) {
            this.attrRef = value;
        }

        /**
         * Gets the value of the literal property.
         * 
         * @return possible object is {@link JAXBElement }{@code <}
         *         {@link BinaryOperation.Literal }{@code >}
         * 
         */
        public JAXBElement<BinaryOperation.Literal> getLiteral() {
            return literal;
        }

        /**
         * Sets the value of the literal property.
         * 
         * @param value
         *            allowed object is {@link JAXBElement }{@code <}
         *            {@link BinaryOperation.Literal }{@code >}
         * 
         */
        public void setLiteral(JAXBElement<BinaryOperation.Literal> value) {
            this.literal = ((JAXBElement<BinaryOperation.Literal>) value);
        }

        /**
         * Gets the value of the paramRef property.
         * 
         * @return possible object is {@link BinaryOperation.ParamRef }
         * 
         */
        public BinaryOperation.ParamRef getParamRef() {
            return paramRef;
        }

        /**
         * Sets the value of the paramRef property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation.ParamRef }
         * 
         */
        public void setParamRef(BinaryOperation.ParamRef value) {
            this.paramRef = value;
        }

        /**
         * Gets the value of the array property.
         * 
         * @return possible object is {@link BinaryOperation.Array }
         * 
         */
        public BinaryOperation.Array getArray() {
            return array;
        }

        /**
         * Sets the value of the array property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation.Array }
         * 
         */
        public void setArray(BinaryOperation.Array value) {
            this.array = value;
        }

        /**
         * Gets the value of the functionCall property.
         * 
         * @return possible object is {@link BinaryOperation.FunctionCall }
         * 
         */
        public BinaryOperation.FunctionCall getFunctionCall() {
            return functionCall;
        }

        /**
         * Sets the value of the functionCall property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation.FunctionCall }
         * 
         */
        public void setFunctionCall(BinaryOperation.FunctionCall value) {
            this.functionCall = value;
        }

        /**
         * Gets the value of the group property.
         * 
         * @return possible object is {@link BinaryOperation.Group }
         * 
         */
        public BinaryOperation.Group getGroup() {
            return group;
        }

        /**
         * Sets the value of the group property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation.Group }
         * 
         */
        public void setGroup(BinaryOperation.Group value) {
            this.group = value;
        }

        /**
         * Gets the value of the comparison property.
         * 
         * @return possible object is {@link BinaryOperation }
         * 
         */
        public BinaryOperation getComparison() {
            return comparison;
        }

        /**
         * Sets the value of the comparison property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation }
         * 
         */
        public void setComparison(BinaryOperation value) {
            this.comparison = value;
        }

        /**
         * Gets the value of the connective property.
         * 
         * @return possible object is {@link BinaryOperation }
         * 
         */
        public BinaryOperation getConnective() {
            return connective;
        }

        /**
         * Sets the value of the connective property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation }
         * 
         */
        public void setConnective(BinaryOperation value) {
            this.connective = value;
        }

        /**
         * Gets the value of the not property.
         * 
         * @return possible object is {@link UnaryOperation }
         * 
         */
        public UnaryOperation getNot() {
            return not;
        }

        /**
         * Sets the value of the not property.
         * 
         * @param value
         *            allowed object is {@link UnaryOperation }
         * 
         */
        public void setNot(UnaryOperation value) {
            this.not = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}QName" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Literal {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected QName type;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return possible object is {@link QName }
         * 
         */
        public QName getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *            allowed object is {@link QName }
         * 
         */
        public void setType(QName value) {
            this.type = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class ParamRef {

        @XmlValue
        protected String value;
        @XmlAttribute(required = true)
        protected int id;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

    }

}
