//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:54:57 AM EDT 
//

package com.trp.pub.cust.model.xml1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Message-v1.0 complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Message-v1.0">
 *   &lt;complexContent>
 *     &lt;extension base="{http://trp/inv/cmm/1.0}AbstractMessage">
 *       &lt;sequence>
 *         &lt;element name="Body" type="{http://trp/inv/cmm/1.0}MessageBody"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message-v1.0", propOrder = { "body" })
public class MessageV10 extends AbstractMessage {

    @XmlElement(name = "Body", required = true)
    protected MessageBody body;

    /**
     * Gets the value of the body property.
     * 
     * @return possible object is {@link MessageBody }
     * 
     */
    public MessageBody getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *            allowed object is {@link MessageBody }
     * 
     */
    public void setBody(MessageBody value) {
        this.body = value;
    }

}
