//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:54:57 AM EDT 
//

package com.trp.pub.cust.model.xml1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.trp.pub.cust.model.xml1 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Feed_QNAME = new QName(
            "http://trp/inv/cmm/1.0", "Feed");
    private static final QName _Message_QNAME = new QName(
            "http://trp/inv/cmm/1.0", "Message");
    private static final QName _FeedFile_QNAME = new QName(
            "http://trp/inv/cmm/1.0", "FeedFile");
    private static final QName _BinaryOperationGroupLiteral_QNAME = new QName(
            "http://trp/inv/atlas/1.0", "Literal");
    private static final QName _BinaryOperationFunctionCallConstant_QNAME = new QName(
            "http://trp/inv/atlas/1.0", "Constant");
    private static final QName _BinaryOperationFunctionCallComparison_QNAME = new QName(
            "http://trp/inv/atlas/1.0", "Comparison");
    private static final QName _BinaryOperationFunctionCallNot_QNAME = new QName(
            "http://trp/inv/atlas/1.0", "Not");
    private static final QName _BinaryOperationFunctionCallGroup_QNAME = new QName(
            "http://trp/inv/atlas/1.0", "Group");
    private static final QName _BinaryOperationFunctionCallFunctionCall_QNAME = new QName(
            "http://trp/inv/atlas/1.0", "FunctionCall");
    private static final QName _BinaryOperationFunctionCallConnective_QNAME = new QName(
            "http://trp/inv/atlas/1.0", "Connective");
    private static final QName _BinaryOperationFunctionCallAttrRef_QNAME = new QName(
            "http://trp/inv/atlas/1.0", "AttrRef");
    private static final QName _BinaryOperationFunctionCallArray_QNAME = new QName(
            "http://trp/inv/atlas/1.0", "Array");
    private static final QName _BinaryOperationFunctionCallParamRef_QNAME = new QName(
            "http://trp/inv/atlas/1.0", "ParamRef");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: com.trp.pub.cust.model.xml1
     * 
     */
    public ObjectFactory() {
        /*
         * no-op
         */
    }

    /**
     * Create an instance of {@link BinaryOperation.Literal }
     * 
     */
    public BinaryOperation.Literal createBinaryOperationLiteral() {
        return new BinaryOperation.Literal();
    }

    /**
     * Create an instance of {@link IssuePublicationV10 }
     * 
     */
    public IssuePublicationV10 createIssuePublicationV10() {
        return new IssuePublicationV10();
    }

    /**
     * Create an instance of {@link QueryPlan.Result.Attr }
     * 
     */
    public QueryPlan.Result.Attr createQueryPlanResultAttr() {
        return new QueryPlan.Result.Attr();
    }

    /**
     * Create an instance of {@link UnaryOperation }
     * 
     */
    public UnaryOperation createUnaryOperation() {
        return new UnaryOperation();
    }

    /**
     * Create an instance of {@link DataQueryV10 .Sort }
     * 
     */
    public DataQueryV10.Sort createDataQueryV10Sort() {
        return new DataQueryV10.Sort();
    }

    /**
     * Create an instance of {@link Selector.Param }
     * 
     */
    public Selector.Param createSelectorParam() {
        return new Selector.Param();
    }

    /**
     * Create an instance of {@link DocumentRefV10 .Part }
     * 
     */
    public DocumentRefV10.Part createDocumentRefV10Part() {
        return new DocumentRefV10.Part();
    }

    /**
     * Create an instance of {@link DatasetKeys }
     * 
     */
    public DatasetKeys createDatasetKeys() {
        return new DatasetKeys();
    }

    /**
     * Create an instance of {@link BinaryOperation.Group }
     * 
     */
    public BinaryOperation.Group createBinaryOperationGroup() {
        return new BinaryOperation.Group();
    }

    /**
     * Create an instance of {@link Dataset }
     * 
     */
    public Dataset createDataset() {
        return new Dataset();
    }

    /**
     * Create an instance of {@link DataQueryV10 .Argument }
     * 
     */
    public DataQueryV10.Argument createDataQueryV10Argument() {
        return new DataQueryV10.Argument();
    }

    /**
     * Create an instance of {@link QueryContext }
     * 
     */
    public QueryContext createQueryContext() {
        return new QueryContext();
    }

    /**
     * Create an instance of {@link DocumentRefV10 .Property }
     * 
     */
    public DocumentRefV10.Property createDocumentRefV10Property() {
        return new DocumentRefV10.Property();
    }

    /**
     * Create an instance of {@link BinaryOperation.FunctionCall }
     * 
     */
    public BinaryOperation.FunctionCall createBinaryOperationFunctionCall() {
        return new BinaryOperation.FunctionCall();
    }

    /**
     * Create an instance of {@link Template }
     * 
     */
    public Template createTemplate() {
        return new Template();
    }

    /**
     * Create an instance of {@link Selector }
     * 
     */
    public Selector createSelector() {
        return new Selector();
    }

    /**
     * Create an instance of {@link DataAvailableV10 }
     * 
     */
    public DataAvailableV10 createDataAvailableV10() {
        return new DataAvailableV10();
    }

    /**
     * Create an instance of {@link BinaryOperation.ParamRef }
     * 
     */
    public BinaryOperation.ParamRef createBinaryOperationParamRef() {
        return new BinaryOperation.ParamRef();
    }

    /**
     * Create an instance of {@link BinaryOperation.AttrRef }
     * 
     */
    public BinaryOperation.AttrRef createBinaryOperationAttrRef() {
        return new BinaryOperation.AttrRef();
    }

    /**
     * Create an instance of {@link QueryPlan }
     * 
     */
    public QueryPlan createQueryPlan() {
        return new QueryPlan();
    }

    /**
     * Create an instance of {@link TemplateKeys }
     * 
     */
    public TemplateKeys createTemplateKeys() {
        return new TemplateKeys();
    }

    /**
     * Create an instance of {@link Dataset.Attr }
     * 
     */
    public Dataset.Attr createDatasetAttr() {
        return new Dataset.Attr();
    }

    /**
     * Create an instance of {@link QueryPlan.Result }
     * 
     */
    public QueryPlan.Result createQueryPlanResult() {
        return new QueryPlan.Result();
    }

    /**
     * Create an instance of {@link DocumentV10 }
     * 
     */
    public DocumentV10 createDocumentV10() {
        return new DocumentV10();
    }

    /**
     * Create an instance of {@link Selector.Expression }
     * 
     */
    public Selector.Expression createSelectorExpression() {
        return new Selector.Expression();
    }

    /**
     * Create an instance of {@link DocumentV10 .Property }
     * 
     */
    public DocumentV10.Property createDocumentV10Property() {
        return new DocumentV10.Property();
    }

    /**
     * Create an instance of {@link TemplateKeys.TemplateKey }
     * 
     */
    public TemplateKeys.TemplateKey createTemplateKeysTemplateKey() {
        return new TemplateKeys.TemplateKey();
    }

    /**
     * Create an instance of {@link DataQueryV10 }
     * 
     */
    public DataQueryV10 createDataQueryV10() {
        return new DataQueryV10();
    }

    /**
     * Create an instance of {@link DocumentRefV10 }
     * 
     */
    public DocumentRefV10 createDocumentRefV10() {
        return new DocumentRefV10();
    }

    /**
     * Create an instance of {@link MessageV10 }
     * 
     */
    public MessageV10 createMessageV10() {
        return new MessageV10();
    }

    /**
     * Create an instance of {@link Selector.Attr }
     * 
     */
    public Selector.Attr createSelectorAttr() {
        return new Selector.Attr();
    }

    /**
     * Create an instance of {@link DatasetKeys.DatasetKey }
     * 
     */
    public DatasetKeys.DatasetKey createDatasetKeysDatasetKey() {
        return new DatasetKeys.DatasetKey();
    }

    /**
     * Create an instance of {@link BinaryOperation.Array }
     * 
     */
    public BinaryOperation.Array createBinaryOperationArray() {
        return new BinaryOperation.Array();
    }

    /**
     * Create an instance of {@link BinaryOperation }
     * 
     */
    public BinaryOperation createBinaryOperation() {
        return new BinaryOperation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/cmm/1.0", name = "Feed")
    public JAXBElement<String> createFeed(String value) {
        return new JAXBElement<String>(_Feed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractMessage }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/cmm/1.0", name = "Message")
    public JAXBElement<AbstractMessage> createMessage(AbstractMessage value) {
        return new JAXBElement<AbstractMessage>(_Message_QNAME,
                AbstractMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/cmm/1.0", name = "FeedFile")
    public JAXBElement<String> createFeedFile(String value) {
        return new JAXBElement<String>(_FeedFile_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Literal }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Literal", scope = BinaryOperation.Group.class)
    public JAXBElement<BinaryOperation.Literal> createBinaryOperationGroupLiteral(
            BinaryOperation.Literal value) {
        return new JAXBElement<BinaryOperation.Literal>(
                _BinaryOperationGroupLiteral_QNAME,
                BinaryOperation.Literal.class, BinaryOperation.Group.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Literal }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Literal", scope = UnaryOperation.class)
    public JAXBElement<BinaryOperation.Literal> createUnaryOperationLiteral(
            BinaryOperation.Literal value) {
        return new JAXBElement<BinaryOperation.Literal>(
                _BinaryOperationGroupLiteral_QNAME,
                BinaryOperation.Literal.class, UnaryOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Literal }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Literal", scope = Selector.Expression.class)
    public JAXBElement<BinaryOperation.Literal> createSelectorExpressionLiteral(
            BinaryOperation.Literal value) {
        return new JAXBElement<BinaryOperation.Literal>(
                _BinaryOperationGroupLiteral_QNAME,
                BinaryOperation.Literal.class, Selector.Expression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Constant", scope = BinaryOperation.FunctionCall.class)
    public JAXBElement<String> createBinaryOperationFunctionCallConstant(
            String value) {
        return new JAXBElement<String>(
                _BinaryOperationFunctionCallConstant_QNAME, String.class,
                BinaryOperation.FunctionCall.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BinaryOperation }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Comparison", scope = BinaryOperation.FunctionCall.class)
    public JAXBElement<BinaryOperation> createBinaryOperationFunctionCallComparison(
            BinaryOperation value) {
        return new JAXBElement<BinaryOperation>(
                _BinaryOperationFunctionCallComparison_QNAME,
                BinaryOperation.class, BinaryOperation.FunctionCall.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnaryOperation }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Not", scope = BinaryOperation.FunctionCall.class)
    public JAXBElement<UnaryOperation> createBinaryOperationFunctionCallNot(
            UnaryOperation value) {
        return new JAXBElement<UnaryOperation>(
                _BinaryOperationFunctionCallNot_QNAME, UnaryOperation.class,
                BinaryOperation.FunctionCall.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Group }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Group", scope = BinaryOperation.FunctionCall.class)
    public JAXBElement<BinaryOperation.Group> createBinaryOperationFunctionCallGroup(
            BinaryOperation.Group value) {
        return new JAXBElement<BinaryOperation.Group>(
                _BinaryOperationFunctionCallGroup_QNAME,
                BinaryOperation.Group.class,
                BinaryOperation.FunctionCall.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.FunctionCall }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "FunctionCall", scope = BinaryOperation.FunctionCall.class)
    public JAXBElement<BinaryOperation.FunctionCall> createBinaryOperationFunctionCallFunctionCall(
            BinaryOperation.FunctionCall value) {
        return new JAXBElement<BinaryOperation.FunctionCall>(
                _BinaryOperationFunctionCallFunctionCall_QNAME,
                BinaryOperation.FunctionCall.class,
                BinaryOperation.FunctionCall.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BinaryOperation }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Connective", scope = BinaryOperation.FunctionCall.class)
    public JAXBElement<BinaryOperation> createBinaryOperationFunctionCallConnective(
            BinaryOperation value) {
        return new JAXBElement<BinaryOperation>(
                _BinaryOperationFunctionCallConnective_QNAME,
                BinaryOperation.class, BinaryOperation.FunctionCall.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.AttrRef }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "AttrRef", scope = BinaryOperation.FunctionCall.class)
    public JAXBElement<BinaryOperation.AttrRef> createBinaryOperationFunctionCallAttrRef(
            BinaryOperation.AttrRef value) {
        return new JAXBElement<BinaryOperation.AttrRef>(
                _BinaryOperationFunctionCallAttrRef_QNAME,
                BinaryOperation.AttrRef.class,
                BinaryOperation.FunctionCall.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Array }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Array", scope = BinaryOperation.FunctionCall.class)
    public JAXBElement<BinaryOperation.Array> createBinaryOperationFunctionCallArray(
            BinaryOperation.Array value) {
        return new JAXBElement<BinaryOperation.Array>(
                _BinaryOperationFunctionCallArray_QNAME,
                BinaryOperation.Array.class,
                BinaryOperation.FunctionCall.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.ParamRef }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "ParamRef", scope = BinaryOperation.FunctionCall.class)
    public JAXBElement<BinaryOperation.ParamRef> createBinaryOperationFunctionCallParamRef(
            BinaryOperation.ParamRef value) {
        return new JAXBElement<BinaryOperation.ParamRef>(
                _BinaryOperationFunctionCallParamRef_QNAME,
                BinaryOperation.ParamRef.class,
                BinaryOperation.FunctionCall.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Literal }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Literal", scope = BinaryOperation.FunctionCall.class)
    public JAXBElement<BinaryOperation.Literal> createBinaryOperationFunctionCallLiteral(
            BinaryOperation.Literal value) {
        return new JAXBElement<BinaryOperation.Literal>(
                _BinaryOperationGroupLiteral_QNAME,
                BinaryOperation.Literal.class,
                BinaryOperation.FunctionCall.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BinaryOperation }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Comparison", scope = BinaryOperation.Array.class)
    public JAXBElement<BinaryOperation> createBinaryOperationArrayComparison(
            BinaryOperation value) {
        return new JAXBElement<BinaryOperation>(
                _BinaryOperationFunctionCallComparison_QNAME,
                BinaryOperation.class, BinaryOperation.Array.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnaryOperation }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Not", scope = BinaryOperation.Array.class)
    public JAXBElement<UnaryOperation> createBinaryOperationArrayNot(
            UnaryOperation value) {
        return new JAXBElement<UnaryOperation>(
                _BinaryOperationFunctionCallNot_QNAME, UnaryOperation.class,
                BinaryOperation.Array.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Group }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Group", scope = BinaryOperation.Array.class)
    public JAXBElement<BinaryOperation.Group> createBinaryOperationArrayGroup(
            BinaryOperation.Group value) {
        return new JAXBElement<BinaryOperation.Group>(
                _BinaryOperationFunctionCallGroup_QNAME,
                BinaryOperation.Group.class, BinaryOperation.Array.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.FunctionCall }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "FunctionCall", scope = BinaryOperation.Array.class)
    public JAXBElement<BinaryOperation.FunctionCall> createBinaryOperationArrayFunctionCall(
            BinaryOperation.FunctionCall value) {
        return new JAXBElement<BinaryOperation.FunctionCall>(
                _BinaryOperationFunctionCallFunctionCall_QNAME,
                BinaryOperation.FunctionCall.class,
                BinaryOperation.Array.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BinaryOperation }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Connective", scope = BinaryOperation.Array.class)
    public JAXBElement<BinaryOperation> createBinaryOperationArrayConnective(
            BinaryOperation value) {
        return new JAXBElement<BinaryOperation>(
                _BinaryOperationFunctionCallConnective_QNAME,
                BinaryOperation.class, BinaryOperation.Array.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.AttrRef }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "AttrRef", scope = BinaryOperation.Array.class)
    public JAXBElement<BinaryOperation.AttrRef> createBinaryOperationArrayAttrRef(
            BinaryOperation.AttrRef value) {
        return new JAXBElement<BinaryOperation.AttrRef>(
                _BinaryOperationFunctionCallAttrRef_QNAME,
                BinaryOperation.AttrRef.class, BinaryOperation.Array.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Array }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Array", scope = BinaryOperation.Array.class)
    public JAXBElement<BinaryOperation.Array> createBinaryOperationArrayArray(
            BinaryOperation.Array value) {
        return new JAXBElement<BinaryOperation.Array>(
                _BinaryOperationFunctionCallArray_QNAME,
                BinaryOperation.Array.class, BinaryOperation.Array.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.ParamRef }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "ParamRef", scope = BinaryOperation.Array.class)
    public JAXBElement<BinaryOperation.ParamRef> createBinaryOperationArrayParamRef(
            BinaryOperation.ParamRef value) {
        return new JAXBElement<BinaryOperation.ParamRef>(
                _BinaryOperationFunctionCallParamRef_QNAME,
                BinaryOperation.ParamRef.class, BinaryOperation.Array.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Literal }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Literal", scope = BinaryOperation.Array.class)
    public JAXBElement<BinaryOperation.Literal> createBinaryOperationArrayLiteral(
            BinaryOperation.Literal value) {
        return new JAXBElement<BinaryOperation.Literal>(
                _BinaryOperationGroupLiteral_QNAME,
                BinaryOperation.Literal.class, BinaryOperation.Array.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BinaryOperation }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Comparison", scope = BinaryOperation.class)
    public JAXBElement<BinaryOperation> createBinaryOperationComparison(
            BinaryOperation value) {
        return new JAXBElement<BinaryOperation>(
                _BinaryOperationFunctionCallComparison_QNAME,
                BinaryOperation.class, BinaryOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnaryOperation }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Not", scope = BinaryOperation.class)
    public JAXBElement<UnaryOperation> createBinaryOperationNot(
            UnaryOperation value) {
        return new JAXBElement<UnaryOperation>(
                _BinaryOperationFunctionCallNot_QNAME, UnaryOperation.class,
                BinaryOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Group }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Group", scope = BinaryOperation.class)
    public JAXBElement<BinaryOperation.Group> createBinaryOperationGroup(
            BinaryOperation.Group value) {
        return new JAXBElement<BinaryOperation.Group>(
                _BinaryOperationFunctionCallGroup_QNAME,
                BinaryOperation.Group.class, BinaryOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.FunctionCall }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "FunctionCall", scope = BinaryOperation.class)
    public JAXBElement<BinaryOperation.FunctionCall> createBinaryOperationFunctionCall(
            BinaryOperation.FunctionCall value) {
        return new JAXBElement<BinaryOperation.FunctionCall>(
                _BinaryOperationFunctionCallFunctionCall_QNAME,
                BinaryOperation.FunctionCall.class, BinaryOperation.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BinaryOperation }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Connective", scope = BinaryOperation.class)
    public JAXBElement<BinaryOperation> createBinaryOperationConnective(
            BinaryOperation value) {
        return new JAXBElement<BinaryOperation>(
                _BinaryOperationFunctionCallConnective_QNAME,
                BinaryOperation.class, BinaryOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.AttrRef }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "AttrRef", scope = BinaryOperation.class)
    public JAXBElement<BinaryOperation.AttrRef> createBinaryOperationAttrRef(
            BinaryOperation.AttrRef value) {
        return new JAXBElement<BinaryOperation.AttrRef>(
                _BinaryOperationFunctionCallAttrRef_QNAME,
                BinaryOperation.AttrRef.class, BinaryOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Array }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Array", scope = BinaryOperation.class)
    public JAXBElement<BinaryOperation.Array> createBinaryOperationArray(
            BinaryOperation.Array value) {
        return new JAXBElement<BinaryOperation.Array>(
                _BinaryOperationFunctionCallArray_QNAME,
                BinaryOperation.Array.class, BinaryOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.ParamRef }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "ParamRef", scope = BinaryOperation.class)
    public JAXBElement<BinaryOperation.ParamRef> createBinaryOperationParamRef(
            BinaryOperation.ParamRef value) {
        return new JAXBElement<BinaryOperation.ParamRef>(
                _BinaryOperationFunctionCallParamRef_QNAME,
                BinaryOperation.ParamRef.class, BinaryOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link BinaryOperation.Literal }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://trp/inv/atlas/1.0", name = "Literal", scope = BinaryOperation.class)
    public JAXBElement<BinaryOperation.Literal> createBinaryOperationLiteral(
            BinaryOperation.Literal value) {
        return new JAXBElement<BinaryOperation.Literal>(
                _BinaryOperationGroupLiteral_QNAME,
                BinaryOperation.Literal.class, BinaryOperation.class, value);
    }

}
