//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:54:57 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://trp/inv/cmm/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
    xmlns = {
            @javax.xml.bind.annotation.XmlNs(prefix = "cmm", namespaceURI = "http://trp/inv/cmm/1.0")    
    }
)
package com.trp.pub.cust.model.xml1;

