//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:54:57 AM EDT 
//

package com.trp.pub.cust.model.xml1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://trp/inv/cmm/1.0}Message"/>
 *         &lt;element ref="{http://trp/inv/atlas/1.0}Selector"/>
 *         &lt;element ref="{http://trp/inv/atlas/1.0}Dataset"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "message", "selector", "dataset" })
@XmlRootElement(name = "QueryContext", namespace = "http://trp/inv/atlas/1.0")
public class QueryContext {

    @XmlElement(name = "Message", required = true)
    protected AbstractMessage message;
    @XmlElement(name = "Selector", namespace = "http://trp/inv/atlas/1.0", required = true)
    protected Selector selector;
    @XmlElement(name = "Dataset", namespace = "http://trp/inv/atlas/1.0", required = true)
    protected Dataset dataset;

    /**
     * Gets the value of the message property.
     * 
     * @return possible object is {@link AbstractMessage }
     * 
     */
    public AbstractMessage getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *            allowed object is {@link AbstractMessage }
     * 
     */
    public void setMessage(AbstractMessage value) {
        this.message = value;
    }

    /**
     * Gets the value of the selector property.
     * 
     * @return possible object is {@link Selector }
     * 
     */
    public Selector getSelector() {
        return selector;
    }

    /**
     * Sets the value of the selector property.
     * 
     * @param value
     *            allowed object is {@link Selector }
     * 
     */
    public void setSelector(Selector value) {
        this.selector = value;
    }

    /**
     * Gets the value of the dataset property.
     * 
     * @return possible object is {@link Dataset }
     * 
     */
    public Dataset getDataset() {
        return dataset;
    }

    /**
     * Sets the value of the dataset property.
     * 
     * @param value
     *            allowed object is {@link Dataset }
     * 
     */
    public void setDataset(Dataset value) {
        this.dataset = value;
    }

}
