//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:54:57 AM EDT 
//

package com.trp.pub.cust.model.xml1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.namespace.QName;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Param" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *                 &lt;attribute name="array" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Attr" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Expression">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://trp/inv/atlas/1.0}Expression"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "param", "attr", "expression" })
@XmlRootElement(name = "Selector", namespace = "http://trp/inv/atlas/1.0")
public class Selector {

    @XmlElement(name = "Param", namespace = "http://trp/inv/atlas/1.0")
    protected List<Selector.Param> param;
    @XmlElement(name = "Attr", namespace = "http://trp/inv/atlas/1.0")
    protected List<Selector.Attr> attr;
    @XmlElement(name = "Expression", namespace = "http://trp/inv/atlas/1.0", required = true)
    protected Selector.Expression expression;

    /**
     * Gets the value of the param property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the param property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Selector.Param }
     * 
     * 
     */
    public List<Selector.Param> getParam() {
        if (param == null) {
            param = new ArrayList<Selector.Param>();
        }
        return this.param;
    }

    /**
     * Gets the value of the attr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the attr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAttr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Selector.Attr }
     * 
     * 
     */
    public List<Selector.Attr> getAttr() {
        if (attr == null) {
            attr = new ArrayList<Selector.Attr>();
        }
        return this.attr;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return possible object is {@link Selector.Expression }
     * 
     */
    public Selector.Expression getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *            allowed object is {@link Selector.Expression }
     * 
     */
    public void setExpression(Selector.Expression value) {
        this.expression = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Attr {

        @XmlValue
        protected String value;
        @XmlAttribute(required = true)
        protected int id;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://trp/inv/atlas/1.0}Expression"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "attrRef", "literal", "paramRef",
            "array", "functionCall", "group", "comparison", "connective", "not" })
    public static class Expression {

        @XmlElement(name = "AttrRef", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation.AttrRef attrRef;
        @XmlElementRef(name = "Literal", namespace = "http://trp/inv/atlas/1.0", type = JAXBElement.class)
        protected JAXBElement<BinaryOperation.Literal> literal;
        @XmlElement(name = "ParamRef", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation.ParamRef paramRef;
        @XmlElement(name = "Array", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation.Array array;
        @XmlElement(name = "FunctionCall", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation.FunctionCall functionCall;
        @XmlElement(name = "Group", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation.Group group;
        @XmlElement(name = "Comparison", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation comparison;
        @XmlElement(name = "Connective", namespace = "http://trp/inv/atlas/1.0")
        protected BinaryOperation connective;
        @XmlElement(name = "Not", namespace = "http://trp/inv/atlas/1.0")
        protected UnaryOperation not;

        /**
         * Gets the value of the attrRef property.
         * 
         * @return possible object is {@link BinaryOperation.AttrRef }
         * 
         */
        public BinaryOperation.AttrRef getAttrRef() {
            return attrRef;
        }

        /**
         * Sets the value of the attrRef property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation.AttrRef }
         * 
         */
        public void setAttrRef(BinaryOperation.AttrRef value) {
            this.attrRef = value;
        }

        /**
         * Gets the value of the literal property.
         * 
         * @return possible object is {@link JAXBElement }{@code <}
         *         {@link BinaryOperation.Literal }{@code >}
         * 
         */
        public JAXBElement<BinaryOperation.Literal> getLiteral() {
            return literal;
        }

        /**
         * Sets the value of the literal property.
         * 
         * @param value
         *            allowed object is {@link JAXBElement }{@code <}
         *            {@link BinaryOperation.Literal }{@code >}
         * 
         */
        public void setLiteral(JAXBElement<BinaryOperation.Literal> value) {
            this.literal = ((JAXBElement<BinaryOperation.Literal>) value);
        }

        /**
         * Gets the value of the paramRef property.
         * 
         * @return possible object is {@link BinaryOperation.ParamRef }
         * 
         */
        public BinaryOperation.ParamRef getParamRef() {
            return paramRef;
        }

        /**
         * Sets the value of the paramRef property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation.ParamRef }
         * 
         */
        public void setParamRef(BinaryOperation.ParamRef value) {
            this.paramRef = value;
        }

        /**
         * Gets the value of the array property.
         * 
         * @return possible object is {@link BinaryOperation.Array }
         * 
         */
        public BinaryOperation.Array getArray() {
            return array;
        }

        /**
         * Sets the value of the array property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation.Array }
         * 
         */
        public void setArray(BinaryOperation.Array value) {
            this.array = value;
        }

        /**
         * Gets the value of the functionCall property.
         * 
         * @return possible object is {@link BinaryOperation.FunctionCall }
         * 
         */
        public BinaryOperation.FunctionCall getFunctionCall() {
            return functionCall;
        }

        /**
         * Sets the value of the functionCall property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation.FunctionCall }
         * 
         */
        public void setFunctionCall(BinaryOperation.FunctionCall value) {
            this.functionCall = value;
        }

        /**
         * Gets the value of the group property.
         * 
         * @return possible object is {@link BinaryOperation.Group }
         * 
         */
        public BinaryOperation.Group getGroup() {
            return group;
        }

        /**
         * Sets the value of the group property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation.Group }
         * 
         */
        public void setGroup(BinaryOperation.Group value) {
            this.group = value;
        }

        /**
         * Gets the value of the comparison property.
         * 
         * @return possible object is {@link BinaryOperation }
         * 
         */
        public BinaryOperation getComparison() {
            return comparison;
        }

        /**
         * Sets the value of the comparison property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation }
         * 
         */
        public void setComparison(BinaryOperation value) {
            this.comparison = value;
        }

        /**
         * Gets the value of the connective property.
         * 
         * @return possible object is {@link BinaryOperation }
         * 
         */
        public BinaryOperation getConnective() {
            return connective;
        }

        /**
         * Sets the value of the connective property.
         * 
         * @param value
         *            allowed object is {@link BinaryOperation }
         * 
         */
        public void setConnective(BinaryOperation value) {
            this.connective = value;
        }

        /**
         * Gets the value of the not property.
         * 
         * @return possible object is {@link UnaryOperation }
         * 
         */
        public UnaryOperation getNot() {
            return not;
        }

        /**
         * Sets the value of the not property.
         * 
         * @param value
         *            allowed object is {@link UnaryOperation }
         * 
         */
        public void setNot(UnaryOperation value) {
            this.not = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
     *       &lt;attribute name="array" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Param {

        @XmlValue
        protected String value;
        @XmlAttribute(required = true)
        protected int id;
        @XmlAttribute(required = true)
        protected QName type;
        @XmlAttribute
        protected Boolean array;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return possible object is {@link QName }
         * 
         */
        public QName getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *            allowed object is {@link QName }
         * 
         */
        public void setType(QName value) {
            this.type = value;
        }

        /**
         * Gets the value of the array property.
         * 
         * @return possible object is {@link Boolean }
         * 
         */
        public Boolean isArray() {
            return array;
        }

        /**
         * Sets the value of the array property.
         * 
         * @param value
         *            allowed object is {@link Boolean }
         * 
         */
        public void setArray(Boolean value) {
            this.array = value;
        }

    }

}
